config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :follows
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  if Rails.env.production?
    constraints(host: /^(?!www\.)/i) do
      match '(*any)', to: redirect { |params, request|
        URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
      }, via: :all
    end
  end
  root "marketplace/home#index"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: 'passwords'
  }
  devise_scope :user do
    get '/password_instructions', to: 'passwords#show_instructions'
    get '/signup_success', to: 'users/registrations#signup_success', as: 'signup_success'
  end
  # config/routes.rb

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get '/sitemap.xml', to: 'application#show_sitemap', format: :xml

  # Defines the root path route ("/")

  get "privacy", to: "home#privacy"
  get "explore", to: "home#explore"
  get "terms", to: "home#terms"
  get "refund_policy", to: "home#refund_policy"
  get "contact", to: "home#contact"
  get "robots.txt", to: "home#robots"

  get "dashboard", to: "dashboard#index"
  get "seller_dashboard", to: "dashboard#seller_dashboard"

  get "complete_registrations", to: "complete_registrations#index"
  put "complete_registration", to: "complete_registrations#update"

  get "complete_developer_registrations", to: "complete_developer_registrations#index"
  put "complete_developer_registration", to: "complete_developer_registrations#update"


  resources :accounts

  resources :products, only: [:index, :show, :edit, :update,:new, :create, :destroy] do
    resources :covers, only: [:create, :destroy], controller: "product_covers"
    post 'like', on: :member
    post 'unlike', on: :member
    get 'search', on: :collection
  end
  get 'search_repositories/(:query)', to: "products#search_repositories"

  resources :subscribed_users, only: :create


  resources :sales, only: [:index, :show]
  resources :funds, only: [:index, :create]
  resources :blogs, param: :slug

  get "coming_soon", to: "coming_soon#index"
  get "index_deploy", to: "coming_soon#index_deploy"
  get "index_jobs", to: "coming_soon#index_jobs"
  get "index_versioning", to: "coming_soon#index_versioning"
  get "index_messages", to: "coming_soon#index_messages"
  get "landing_page", to: "coming_soon#landing_page"
  get "faq", to: "faq#index"
  get "resources", to: "marketplace/home#resources"
  
  namespace :marketplace do
    root "home#index"
    get "browse", to: "browse#index"
    get "browse/popular", to: "browse#popular"
     get "browse/free", to: "browse#free"
      get "browse/premium", to: "browse#premium"
    get "browse/featured", to: "browse#featured"

    get "browse/recent", to: "browse#recent"
    get "browse/languages", to: "browse#languages"
    get "browse/categories", to: "browse#categories"
    resources :creators, only: [:index, :show]
    resources :languages, only: :show, param: :slug
    resources :categories, only: [:show, :create], param: :slug
    resources :library, only: :show, path: "l" do
      resources :reviews, only: [:new, :create]
    end
    resources :purchases, only: [:index]
    resources :cart_items, only: [:index, :create, :destroy]
    get "checkout", to: "checkout#index"
    post "checkout", to: "checkout#create"
    post "refund_payment", to: "checkout#refund"
    get '/success_payment', to: 'checkout#success_payment', as: 'success_payment'
    get '/cancel_payment', to: 'checkout#cancel_payment', as: 'cancel_payment'
    resources :refunds, only: [:new, :create]
    resources :users, only: [:show, :edit, :update, :destroy] do
      resources :products, only: :index, controller: "users/products"
      get :synchronizations, to: "users/synchronizations#show", on: :member
      put :product_activations, to: "users/product_activations#update", on: :member
      member do
        get 'followers', to: 'users#followers', as: 'user_followers'
        get 'followees', to: 'users#followees', as: 'user_followees'
      end
    end
    post '/users/:id/follow', to: "users#follow", as: "follow_user"
    post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
    get "search", to: "search_results#index"
    
    resources :notifications, only: [:index] do
      member do
        get :mark_as_read
      end
      collection do
        get :mark_all_as_read
      end
    end
  end

  # Error Pages
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def privacy
  end

  def terms
  end

  def refund_policy
  end

  def contact
  end

  def explore
    current_user.update(state: User.states[:buyer])
    redirect_to marketplace_root_path
  end

  def robots
    respond_to :text
  end
end

app/controllers/marketplace/home_controller.rb
module Marketplace
  class HomeController < ApplicationController
    def index
      # redirect_to dashboard_path if user_signed_in? && current_user.token.present?
      # redirect_to landing_page_path if !user_signed_in?
      @product_count = Product.count 
      @category_count = Category.count 
      @languag_count = Language.count 
      @languages = Language.order(:name).limit(20)
      @categories = Category.order(:name).limit(20)
      @creators = User.order(total_earning: :desc).limit(20)
      @recent_products = Product.with_attached_covers.published.includes([:languages]).recent.exclude_purchased(current_user).first(15)
      @popular_products = Product.with_attached_covers.includes([:languages]).ordered_by_purchase_count.first(15)
      @free_products = Product.with_attached_covers.includes([:languages]).where("price_cents <= 0").order(created_at: :desc).first(15)
      @premium_products = Product.with_attached_covers.includes([:languages]).where("price_cents > 0").order(created_at: :desc).first(15)
      @featured_products = Product.with_attached_covers.includes([:languages]).where(featured: true)

      @creators = recently_subscribed()
    end
    def resources
    
    end

    def recently_subscribed
      recently_followed_users = User.joins(:following_users).order('follows.created_at DESC').limit(20)
      followed_user_ids = recently_followed_users.pluck(:id)
      remaining_limit = 20 - recently_followed_users.count

      not_followed_users = User.where.not(id: followed_user_ids).limit(remaining_limit)
      @creators = recently_followed_users + not_followed_users
    end
  end
end

app/views/home/_category.html.erb
<%= link_to marketplace_category_path(category.slug), class: "relative aspect-square border border-black border-4 rounded hover:shadow-[0px_20px_20px_15px_#1a202c] hover:scale-105" do %>
  <%= image_tag "categories/#{category.image_name}", class: "h-full w-full aspect-square object-cover object-center rounded" %>
  <div class="absolute rounded-b border-4 bottom-0 flex items-center right-0 left-0 bg-gradient-to-b from-transparent to-gray-300 ">
    <div class="bg-white rounded-3xl flex items-center">
    <p class="p-3 w-full text-center text-sm font-bold font-mono text-black"><%= category.name %></p>
    </div>
  </div>
<% end %>

app/views/home/_creator.html.erb
<%= link_to marketplace_creator_path(creator.id), class: "relative flex h-48 flex-col overflow-hidden rounded-lg p-6 hover:opacity-75 md:w-56 lg:w-64 xl:w-auto" do %>
  <span aria-hidden="true" class="absolute inset-0">
    <% if creator.profile_picture.attached? %>
      <%= image_tag creator.profile_picture, class: "h-full w-full object-cover object-center", style: "object-fit: contain;" %>
    <% else %>
      <%= image_tag "profile_placeholder.png", class: "h-full w-full object-cover object-center", style: "object-fit: inherit;" %>
    <% end %>
  </span>
  <span aria-hidden="true" class="absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-gray-800 opacity-50"></span>
  <span class="relative mt-auto text-center text-xl font-bold text-white"><%= creator.username %></span>
<% end %>

app/views/home/_intro_modal.html.erb
<div class="flex justify-center">
  <iframe
    width="560"
    height="315"
    class="w-full"
    src="https://www.youtube.com/embed/XLZpR8gN9hc?si=0lsZRxORY9nGpjyT"
    title="YouTube video player"
    frameborder="0"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
    allowfullscreen>
  </iframe>
</div>

<div
  data-controller="intro-dialog"
  data-api-url="<%= subscribed_users_url %>"
>
  <div
    data-intro-dialog-target="emailForm"
    class="grid grid-cols-5 gap-1 mt-6"
  >
    <div class="relative w-full col-span-4">
      <div class="absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none">
        <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16">
          <path d="m10.036 8.278 9.258-7.79A1.979 1.979 0 0 0 18 0H2A1.987 1.987 0 0 0 .641.541l9.395 7.737Z"/>
          <path d="M11.241 9.817c-.36.275-.801.425-1.255.427-.428 0-.845-.138-1.187-.395L0 2.6V14a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V2.5l-8.759 7.317Z"/>
        </svg>
      </div>
      <input
        data-intro-dialog-target="emailInput"
        type="text"
        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
        placeholder="Your email address..."
      >
    </div>

    <div class="col-span-1">
      <button
        data-action="click->intro-dialog#subscribeToEmail"
        type="button"
        class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
      >
        Subscribe
      </button>
    </div>
  </div>

  <div
    data-intro-dialog-target="subscribed"
    class="mt-6 flex justify-center hidden"
  >
    <p class="text-green-600 font-semibold">Subscribed!</p>
  </div>
</div>

app/views/home/_language.html.erb
<%= link_to marketplace_language_path(language.slug), class: "relative aspect-square border border-black border-4 rounded hover:shadow-[0px_20px_20px_15px_#1a202c] hover:scale-105" do %>
  <%= image_tag "languages/#{language.image_name}", class: "h-full w-full aspect-square object-cover object-center rounded" %>
  <div class="absolute rounded-b border-4 bottom-0 flex items-center right-0 left-0 bg-gradient-to-b from-transparent to-gray-300 ">
    <div class="bg-white rounded-3xl flex items-center">
    <p class="p-3 w-full text-center text-sm font-bold font-mono text-black"><%= language.name %></p>
    </div>
  </div>
<% end %>

app/views/home/_product.html.erb
<div class="bg-white rounded-lg border-6" data-controller="product-card">
  <div class="border h-full border-black rounded-lg hover:shadow-[0px_20px_20px_15px_#1a202c] flex flex-col divide-y divide-black">
    <%= link_to marketplace_library_path(product), class:"h-full" do %>
      <div class="h-full grow flex flex-col divide-y divide-black">
        <%# Cover Image %>
        <div class="bg-gray-100 aspect-w-1 aspect-h-1 overflow-hidden rounded-t">
          <% if product.covers.first.present? %>
            <img src="<%= product.thumb_image_url %>" alt="TODO" class="h-full w-full object-cover object-center">
          <% else %>
            <img src="<%= asset_path('default-cover.png') %>" alt="No Image Available" class="h-full w-full object-cover object-center">
          <% end %>
        </div>

        <div class="grow p-3 flex flex-col gap-4">
          <h3 class="grow text-base font-medium text-black font-mono line-clamp-2">
            <%= product.name %>
          </h3>

          <%# Languages %>
          <% if product.languages.present? && product.languages.size > 0 && product.languages[0]&.name != 'not_specified' || product.more_languages_from_createor.present? %>
            <div class="flex flex-row flex-wrap items-center justify-start gap-2">
              <% product.languages&.take(3).each do |language| %>
                <p class="text-xs border border-gray-900 rounded px-2 py-1.5 text-gray-700"><%= language.name %></p>
              <% end %>
              
              <% product.more_languages_from_createor&.take(2).each do |lang| %>
                <p class="text-xs border border-gray-900 rounded px-2 py-1.5 text-gray-700"><%= lang %></p>
              <% end %>
            </div>
          <% end %>
  
        </div>

        <%# Reviews + Price %>
        <div class="flex flex-row items-center divide-x divide-black p-0 m-0">
          <%# Reviews %>
          <div class="p-3 grid grid-cols-2 grow">
            <% if product.reviews.size > 0 %> 
              <div class="flex items-center gap-1">
                <svg class="text-gray-700 h-4 w-4 flex-shrink-0" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M10.868 2.884c-.321-.772-1.415-.772-1.736 0l-1.83 4.401-4.753.381c-.833.067-1.171 1.107-.536 1.651l3.62 3.102-1.106 4.637c-.194.813.691 1.456 1.405 1.02L10 15.591l4.069 2.485c.713.436 1.598-.207 1.404-1.02l-1.106-4.637 3.62-3.102c.635-.544.297-1.584-.536-1.65l-4.752-.382-1.831-4.401z" clip-rule="evenodd" />
                </svg>
                <p class="px-1 py-1 text-sm font-medium text-gray-700"><%= product.average_rating.to_f.round(1) %>(<%= product.reviews.size %>)</p>
              </div>
            <% else %>
              <div class="flex items-center">
                <p class="px-1 py-1 rounded text-sm font-medium bg-green-500 text-black">New</p>
              </div>
            <% end %>
            <% if product.featured %>
	      <div class="flex justify-center items-center">
                <p class="px-1 py-1 rounded text-sm font-medium bg-indigo-300 text-black">Featured</p>
              </div>
	    <% end %>
          </div>
          <%# Price %>
          <div class="p-3">
            <% if product.price.to_f.round(2) > 0.00 %> 
              <p class="px-1 py-1 text-sm font-medium text-black"><%= product.price.currency.symbol %><%= product.price %></p>
            <% else %>
              <p class="px-1 py-1 rounded text-sm font-medium bg-yellow-500 text-black">Free</p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <%# Download %>
    <% if policy(product).download_able? %>
      <div class="p-3">
        <%= link_to "Download", product.folder.url , data: { "turbo-method": :post }, class: "flex w-full items-center justify-center rounded-md border border-transparent bg-indigo-600 px-3 py-2 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-50" %>
      </div>
    <% end %>
  </div>
</div>

app/views/home/contact.html.erb
<% content_for :meta_title, "Contact Us" %>
<% content_for :meta_description,  "Contact GitLocker Representative here" %>
<div class="pt-16 sm:pt-16 xl:mx-auto xl:px-8 bg-gradient-to-r from-blue-700 to-orange-500" style=" min-height: 34.46rem";>
  <h1 class="text-3xl underline font-mono">Contact Info:</h1>
  <p>Please contact <%= mail_to "cody@gitlocker.com", class: "text-black" %> if you have any questions, concerns, issues, tips, or guest post inquiries. We charge $200 per guest post. The guest posts must be related to coding or software and are subject for review by our team. If any content posted on our website violates any licenses that you have on your products please shoot us an email and we will have those products removed.</p>
</div>

app/views/home/index.html.erb
<!--
  This example requires some changes to your config:

  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/forms'),
      require('@tailwindcss/aspect-ratio'),
    ],
  }
  ```
-->
<div class="bg-white">
  <main>
    <section aria-labelledby="category-heading" class="pt-16 sm:pt-16 xl:mx-auto xl:max-w-7xl xl:px-8">
      <div class="px-4 sm:flex sm:items-center sm:justify-between sm:px-6 lg:px-8 xl:px-0">
        <h2 id="category-heading" class="text-2xl font-bold tracking-tight text-gray-900">Recent</h2>
        <%= link_to browse_recent_path, class: "hidden text-sm font-semibold text-indigo-600 hover:text-indigo-500 sm:block" do %>
          Browse All Recent Repositories
          <span aria-hidden="true"> &rarr;</span>
        <% end %>
      </div>

      <div class="mt-4 flow-root">
        <div class="-my-2">
          <div class="relative box-content h-80 overflow-x-auto py-2 xl:overflow-visible">
            <div class="absolute flex space-x-8 px-4 sm:px-6 lg:px-8 xl:relative xl:grid xl:grid-cols-5 xl:gap-x-8 xl:space-x-0 xl:px-0">
              <%= render partial: "home/product", collection: @recent_products, as: :product %>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section aria-labelledby="category-heading" class="pt-16 sm:pt-16 xl:mx-auto xl:max-w-7xl xl:px-8">
      <div class="px-4 sm:flex sm:items-center sm:justify-between sm:px-6 lg:px-8 xl:px-0">
        <h2 id="category-heading" class="text-2xl font-bold tracking-tight text-gray-900">Popular</h2>
        <%= link_to browse_popular_path, class: "hidden text-sm font-semibold text-indigo-600 hover:text-indigo-500 sm:block" do %>
          Browse All Popular Repositories
          <span aria-hidden="true"> &rarr;</span>
        <% end %>
      </div>

      <div class="mt-4 flow-root">
        <div class="-my-2">
          <div class="relative box-content h-80 overflow-x-auto py-2 xl:overflow-visible">
            <div class="absolute flex space-x-8 px-4 sm:px-6 lg:px-8 xl:relative xl:grid xl:grid-cols-5 xl:gap-x-8 xl:space-x-0 xl:px-0">
              <%= render partial: "home/product", collection: @popular_products, as: :product %>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section aria-labelledby="category-heading" class="pt-16 pb-24 sm:pt-16 xl:mx-auto xl:max-w-7xl xl:px-8">
      <div class="px-4 sm:flex sm:items-center sm:justify-between sm:px-6 lg:px-8 xl:px-0">
        <h2 id="category-heading" class="text-2xl font-bold tracking-tight text-gray-900">Languages</h2>
        <%= link_to browse_languages_path, class: "hidden text-sm font-semibold text-indigo-600 hover:text-indigo-500 sm:block" do %>
          Browse All Languages
          <span aria-hidden="true"> &rarr;</span>
        <% end %>
      </div>

      <div class="mt-4 flow-root">
        <div class="-my-2">
          <div class="relative py-2">
            <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <%= render partial: "home/language", collection: @languages %>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section aria-labelledby="category-heading" class="pt-16 pb-24 sm:pt-16 xl:mx-auto xl:max-w-7xl xl:px-8">
      <div class="px-4 sm:flex sm:items-center sm:justify-between sm:px-6 lg:px-8 xl:px-0">
        <h2 id="category-heading" class="text-2xl font-bold tracking-tight text-gray-900">Categories</h2>
        <%= link_to browse_languages_path, class: "hidden text-sm font-semibold text-indigo-600 hover:text-indigo-500 sm:block" do %>
          Browse All Categories
          <span aria-hidden="true"> &rarr;</span>
        <% end %>
      </div>

      <div class="mt-4 flow-root">
        <div class="-my-2">
          <div class="relative py-2">
            <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <%= render partial: "home/category", collection: @categories %>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
</div>

<%= render DialogComponent.new(size: "2xl", headline: "Hey, welcome to GitLocker (Coming in July 2024)", body: render("home/intro_modal"), disabled: false) %>

app/views/home/privacy.html.erb
<% content_for :meta_title, "GitLocker Privacy" %>
<% content_for :meta_description,  "GitLocker Privacy Policy" %>
<div class="pt-16 sm:pt-16 xl:mx-auto xl:max-w-7xl xl:px-8"style=" min-height: 34.46rem";>
  <div name="termly-embed" data-id="fb796cc2-1f70-45e4-a8cd-7a20b18c1297"></div>
  <script type="text/javascript">(function(d, s, id) {
    var js, tjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://app.termly.io/embed-policy.min.js";
    tjs.parentNode.insertBefore(js, tjs);
  }(document, 'script', 'termly-jssdk'));</script>
</div>

app/views/home/refund_policy.html.erb
<% content_for :meta_title, "GitLocker Refund Policy" %>
<% content_for :meta_description,  "GitLocker Refund Policy" %>
<div class="pt-16 sm:pt-16 xl:mx-auto xl:max-w-7xl xl:px-8"style=" min-height: 34.46rem";>
  <div name="termly-embed" data-id="f033b018-07d0-429d-89d8-bf3e5c2b732c"></div>
  <script type="text/javascript">(function(d, s, id) {
    var js, tjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://app.termly.io/embed-policy.min.js";
    tjs.parentNode.insertBefore(js, tjs);
  }(document, 'script', 'termly-jssdk'));</script>
</div>

app/views/home/terms.html.erb
<% content_for :meta_title, "GitLocker Terms" %>
<% content_for :meta_description,  "GitLocker Terms and Conditions" %>
<div class="pt-16 sm:pt-16 xl:mx-auto xl:max-w-7xl xl:px-8"style=" min-height: 34.46rem";>
  <div name="termly-embed" data-id="efb533ca-cda6-451a-bd4d-bcb8b5947b5d"></div>
  <script type="text/javascript">(function(d, s, id) {
    var js, tjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://app.termly.io/embed-policy.min.js";
    tjs.parentNode.insertBefore(js, tjs);
  }(document, 'script', 'termly-jssdk'));</script>
</div>