config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :follows
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  if Rails.env.production?
    constraints(host: /^(?!www\.)/i) do
      match '(*any)', to: redirect { |params, request|
        URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
      }, via: :all
    end
  end
  root "marketplace/home#index"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: 'passwords'
  }
  devise_scope :user do
    get '/password_instructions', to: 'passwords#show_instructions'
    get '/signup_success', to: 'users/registrations#signup_success', as: 'signup_success'
  end
  # config/routes.rb

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get '/sitemap.xml', to: 'application#show_sitemap', format: :xml

  # Defines the root path route ("/")

  get "privacy", to: "home#privacy"
  get "explore", to: "home#explore"
  get "terms", to: "home#terms"
  get "refund_policy", to: "home#refund_policy"
  get "contact", to: "home#contact"
  get "robots.txt", to: "home#robots"

  get "dashboard", to: "dashboard#index"
  get "seller_dashboard", to: "dashboard#seller_dashboard"

  get "complete_registrations", to: "complete_registrations#index"
  put "complete_registration", to: "complete_registrations#update"

  get "complete_developer_registrations", to: "complete_developer_registrations#index"
  put "complete_developer_registration", to: "complete_developer_registrations#update"


  resources :accounts

  resources :products, only: [:index, :show, :edit, :update,:new, :create, :destroy] do
    resources :covers, only: [:create, :destroy], controller: "product_covers"
    post 'like', on: :member
    post 'unlike', on: :member
    get 'search', on: :collection
  end
  get 'search_repositories/(:query)', to: "products#search_repositories"

  resources :subscribed_users, only: :create


  resources :sales, only: [:index, :show]
  resources :funds, only: [:index, :create]
  resources :blogs, param: :slug

  get "coming_soon", to: "coming_soon#index"
  get "index_deploy", to: "coming_soon#index_deploy"
  get "index_jobs", to: "coming_soon#index_jobs"
  get "index_versioning", to: "coming_soon#index_versioning"
  get "index_messages", to: "coming_soon#index_messages"
  get "landing_page", to: "coming_soon#landing_page"
  get "faq", to: "faq#index"
  get "resources", to: "marketplace/home#resources"
  
  namespace :marketplace do
    root "home#index"
    get "browse", to: "browse#index"
    get "browse/popular", to: "browse#popular"
     get "browse/free", to: "browse#free"
      get "browse/premium", to: "browse#premium"
    get "browse/featured", to: "browse#featured"

    get "browse/recent", to: "browse#recent"
    get "browse/languages", to: "browse#languages"
    get "browse/categories", to: "browse#categories"
    resources :creators, only: [:index, :show]
    resources :languages, only: :show, param: :slug
    resources :categories, only: [:show, :create], param: :slug
    resources :library, only: :show, path: "l" do
      resources :reviews, only: [:new, :create]
    end
    resources :purchases, only: [:index]
    resources :cart_items, only: [:index, :create, :destroy]
    get "checkout", to: "checkout#index"
    post "checkout", to: "checkout#create"
    post "refund_payment", to: "checkout#refund"
    get '/success_payment', to: 'checkout#success_payment', as: 'success_payment'
    get '/cancel_payment', to: 'checkout#cancel_payment', as: 'cancel_payment'
    resources :refunds, only: [:new, :create]
    resources :users, only: [:show, :edit, :update, :destroy] do
      resources :products, only: :index, controller: "users/products"
      get :synchronizations, to: "users/synchronizations#show", on: :member
      put :product_activations, to: "users/product_activations#update", on: :member
      member do
        get 'followers', to: 'users#followers', as: 'user_followers'
        get 'followees', to: 'users#followees', as: 'user_followees'
      end
    end
    post '/users/:id/follow', to: "users#follow", as: "follow_user"
    post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
    get "search", to: "search_results#index"
    
    resources :notifications, only: [:index] do
      member do
        get :mark_as_read
      end
      collection do
        get :mark_all_as_read
      end
    end
  end

  # Error Pages
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.friendly.find(params[:id])
    @products = @user.products.published
  end
end

app/controllers/marketplace/creators_controller.rb
module Marketplace
class CreatorsController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.filter_and_sort(params).page(params[:page]).per(40)
     respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @user = User.friendly.find(params[:id])
    @products = @user.products.published.page(params[:page]).per(15)
    @languages = @user.languages
    @categories = @user.categories
  end
end
end

app/views/creators/_creator.html.erb
<li class="col-span-1 flex flex-col divide-y divide-gray-200 rounded-lg bg-white text-center shadow">
  <div class="flex flex-1 flex-col p-8">
    <% if user.profile_picture.attached? %>
      <%= image_tag user.profile_picture, class: "mx-auto h-32 w-32 flex-shrink-0 rounded-full" %>
    <% else %>
      <img class="mx-auto h-32 w-32 flex-shrink-0 rounded-full" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60" alt="">
    <% end %>
    <h1 class="mt-6 text-sm font-medium text-gray-900"><%= user.name %></h3>
    <dl class="mt-1 flex flex-grow flex-col justify-between">
      <dt class="sr-only">Title</dt>
      <dd class="text-sm text-gray-500">@<%= user.username %></dd>
    </dl>
  </div>
  <div>
    <div class="-mt-px flex divide-x divide-gray-200">
      <div class="flex w-0 flex-1">
        <%= link_to "View", creator_path(user), class: "relative -mr-px inline-flex w-0 flex-1 items-center justify-center gap-x-3 rounded-bl-lg border border-transparent py-4 text-sm font-semibold text-gray-900" %>
      </div>
    </div>
  </div>
</li>

app/views/creators/_product.html.erb
<li
  data-controller="product-card"
  class="overflow-hidden rounded-xl border border-gray-200"
>
  <div class="flex items-center gap-x-4 border-b border-gray-900/5 bg-gray-50 p-6">
    <% if product.covers.exists? %>
      <%= image_tag product.covers.first, class: "h-12 w-12 flex-none rounded-lg bg-white object-cover ring-1 ring-gray-900/10" %>
    <% else %>
      <%= image_tag "default-cover.png", class: "h-12 w-12 flex-none rounded-lg bg-white object-cover ring-1 ring-gray-900/10" %>
    <% end %>

    <div class="text-sm font-medium leading-6 text-gray-900"><%= product.name %></div>
    <div class="relative ml-auto">
      <button
        type="button"
        data-action="product-card#open"
        class="-m-2.5 block p-2.5 text-gray-400 hover:text-gray-500"
        id="options-menu-0-button"
        aria-expanded="false"
        aria-haspopup="true"
      >
        <span class="sr-only">Open options</span>
        <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path d="M3 10a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zM8.5 10a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zM15.5 8.5a1.5 1.5 0 100 3 1.5 1.5 0 000-3z" />
        </svg>
      </button>

      <div
        data-product-card-target="menu"
        data-transition-enter="transition ease-out duration-100"
        data-transition-enter-start="transform opacity-0 scale-95"
        data-transition-enter-end="transform opacity-100 scale-100"
        data-transition-leave="transition ease-in duration-75"
        data-transition-leave-start="transform opacity-100 scale-100"
        data-transition-leave-end="transform opacity-0 scale-95"
        class="hidden absolute right-0 z-10 mt-0.5 w-32 origin-top-right rounded-md bg-white py-2 shadow-lg ring-1 ring-gray-900/5 focus:outline-none"
        role="menu"
        aria-orientation="vertical"
        aria-labelledby="options-menu-0-button"
        tabindex="-1"
      >
        <!-- Active: "bg-gray-50", Not Active: "" -->
        <%= link_to library_path(product), data: { "product-card-target": "menuItem" }, class: "block px-3 py-1 text-sm leading-6 text-gray-900", role: "menuitem", tabindex: "-1", id: "options-menu-0-item-0" do %>
          View
        <% end %>
      </div>
    </div>
  </div>
  <dl class="-my-3 divide-y divide-gray-100 px-6 py-4 text-sm leading-6">
    <div class="flex justify-between gap-x-4 py-3">
      <dt class="text-gray-500">Average rating</dt>
      <dd class="text-gray-700">
        <%= product.average_rating %>
      </dd>
    </div>
  </dl>
</li>

app/views/creators/index.html.erb
<%=
  render BreadcrumbComponent.new(current_user,[
    { text: "Creators", url: creators_path }
  ])
%>
<main class="pb-4 pt-6 sm:pb-6">
  <div class="space-y-16 py-16 xl:space-y-20">
    <!-- Creators list-->
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="mx-auto max-w-2xl lg:mx-0 lg:max-w-none">
        <div class="flex items-center justify-between mb-12">
          <h2 class="text-base font-semibold leading-7 text-gray-900">List of Creators</h2>
        </div>
        <ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
          <%= render partial: "creators/creator", collection: @users, as: :user %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/creators/show.html.erb
<%=
  render BreadcrumbComponent.new(current_user,[
    { text: "Creators", url: creators_path },
    { text: @user.username, url: creator_path(@user) }
  ])
%>
<main class="pb-4 pt-6 sm:pb-6">
  <div class="space-y-16 py-16 xl:space-y-20">
    <!-- Creators list-->
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="mx-auto max-w-2xl lg:mx-0 lg:max-w-none">
        <div class="flex space-x-8 items-center justify-between mb-12 pb-12 border-b border-black">
          <div class="flex-none">
            <% if @user.profile_picture.attached? %>
              <%= image_tag @user.profile_picture, class: "mx-auto h-32 w-32 flex-shrink-0 rounded-full" %>
            <% else %>
              <img class="mx-auto h-32 w-32 flex-shrink-0 rounded-full" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60" alt="">
            <% end %>
          </div>
          <h1 class="flex-1 text-base font-semibold leading-7 text-gray-900 text-4xl"><%= @user.name %> - <%= link_to "@#{@user.username}", "https://github.com/#{@user.username}", class: "font-semibold leading-6 text-blue-600 hover:text-blue-500", target: :_blank %></h2>
        </div>

        <div class="flex space-x-8 items-center justify-between mb-12">
          <h2 class="flex-1 text-base font-semibold leading-7 text-gray-900 text-2xl">Listed Products</h2>
        </div>

        <% if @products.empty? %>
          <p class="font-medium leading-7 text-gray-900 text-xl">The user has no listed products for sale.</p>
        <% else %>
          <ul role="list" class="mt-6 grid grid-cols-1 gap-x-6 gap-y-8 lg:grid-cols-3 xl:gap-x-8">
            <%= render partial: "creators/product", collection: @products, as: :product %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</main>