config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :follows
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  if Rails.env.production?
    constraints(host: /^(?!www\.)/i) do
      match '(*any)', to: redirect { |params, request|
        URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
      }, via: :all
    end
  end
  root "marketplace/home#index"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: 'passwords'
  }
  devise_scope :user do
    get '/password_instructions', to: 'passwords#show_instructions'
    get '/signup_success', to: 'users/registrations#signup_success', as: 'signup_success'
  end
  # config/routes.rb

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get '/sitemap.xml', to: 'application#show_sitemap', format: :xml

  # Defines the root path route ("/")

  get "privacy", to: "home#privacy"
  get "explore", to: "home#explore"
  get "terms", to: "home#terms"
  get "refund_policy", to: "home#refund_policy"
  get "contact", to: "home#contact"
  get "robots.txt", to: "home#robots"

  get "dashboard", to: "dashboard#index"
  get "seller_dashboard", to: "dashboard#seller_dashboard"

  get "complete_registrations", to: "complete_registrations#index"
  put "complete_registration", to: "complete_registrations#update"

  get "complete_developer_registrations", to: "complete_developer_registrations#index"
  put "complete_developer_registration", to: "complete_developer_registrations#update"


  resources :accounts

  resources :products, only: [:index, :show, :edit, :update,:new, :create, :destroy] do
    resources :covers, only: [:create, :destroy], controller: "product_covers"
    post 'like', on: :member
    post 'unlike', on: :member
    get 'search', on: :collection
  end
  get 'search_repositories/(:query)', to: "products#search_repositories"

  resources :subscribed_users, only: :create


  resources :sales, only: [:index, :show]
  resources :funds, only: [:index, :create]
  resources :blogs, param: :slug

  get "coming_soon", to: "coming_soon#index"
  get "index_deploy", to: "coming_soon#index_deploy"
  get "index_jobs", to: "coming_soon#index_jobs"
  get "index_versioning", to: "coming_soon#index_versioning"
  get "index_messages", to: "coming_soon#index_messages"
  get "landing_page", to: "coming_soon#landing_page"
  get "faq", to: "faq#index"
  get "resources", to: "marketplace/home#resources"
  
  namespace :marketplace do
    root "home#index"
    get "browse", to: "browse#index"
    get "browse/popular", to: "browse#popular"
     get "browse/free", to: "browse#free"
      get "browse/premium", to: "browse#premium"
    get "browse/featured", to: "browse#featured"

    get "browse/recent", to: "browse#recent"
    get "browse/languages", to: "browse#languages"
    get "browse/categories", to: "browse#categories"
    resources :creators, only: [:index, :show]
    resources :languages, only: :show, param: :slug
    resources :categories, only: [:show, :create], param: :slug
    resources :library, only: :show, path: "l" do
      resources :reviews, only: [:new, :create]
    end
    resources :purchases, only: [:index]
    resources :cart_items, only: [:index, :create, :destroy]
    get "checkout", to: "checkout#index"
    post "checkout", to: "checkout#create"
    post "refund_payment", to: "checkout#refund"
    get '/success_payment', to: 'checkout#success_payment', as: 'success_payment'
    get '/cancel_payment', to: 'checkout#cancel_payment', as: 'cancel_payment'
    resources :refunds, only: [:new, :create]
    resources :users, only: [:show, :edit, :update, :destroy] do
      resources :products, only: :index, controller: "users/products"
      get :synchronizations, to: "users/synchronizations#show", on: :member
      put :product_activations, to: "users/product_activations#update", on: :member
      member do
        get 'followers', to: 'users#followers', as: 'user_followers'
        get 'followees', to: 'users#followees', as: 'user_followees'
      end
    end
    post '/users/:id/follow', to: "users#follow", as: "follow_user"
    post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
    get "search", to: "search_results#index"
    
    resources :notifications, only: [:index] do
      member do
        get :mark_as_read
      end
      collection do
        get :mark_all_as_read
      end
    end
  end

  # Error Pages
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user, counter_cache: true, optional: true
  belongs_to :product

  validates :product_id, uniqueness: { scope: :user_id }
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
    @cart_items = (current_user || visitor_user).cart_items.includes(:product)
  end

  def create
    product = Product.find(params[:product_id])
    cart_item = CartItem.create(product: product, user: current_user, session_id: session.id)
    redirect_to marketplace_library_path(product)
  end

  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    if cart_item.user && !CartItem.exists?(user: cart_item.user)
      redirect_to cart_items_path
    else
      redirect_back(fallback_location: marketplace_library_path(cart_item.product))
    end
  end
end

app/controllers/marketplace/cart_items_controller.rb
module Marketplace
class CartItemsController < ApplicationController
  def index
    @cart_items = (current_user || visitor_user).cart_items.includes(:product)
  end

  def create
    product = Product.find(params[:product_id])
    cart_item = CartItem.create(product: product, user: current_user, session_id: session.id)
    redirect_to marketplace_library_path(product)
  end

  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    if cart_item.user && !CartItem.exists?(user: cart_item.user)
      redirect_to marketplace_cart_items_path
    else
      redirect_back(fallback_location: marketplace_library_path(cart_item.product))
    end
  end
end
end

app/views/cart_items/_cart_item.html.erb
<li class="flex py-6 sm:py-10">
  <div class="flex-shrink-0">
    <% if cart_item.product.covers.exists? %>
      <%= image_tag cart_item.product.covers.last, class: "h-24 w-24 rounded-md object-cover object-center sm:h-48 sm:w-48" %>
    <% else %>
      <%= image_tag "default-cover.png", class: "h-24 w-24 rounded-md object-cover object-center sm:h-48 sm:w-48" %>
    <% end %>
  </div>

  <div class="ml-4 flex flex-1 flex-col justify-between sm:ml-6">
    <div class="relative pr-9 sm:grid sm:grid-cols-2 sm:gap-x-6 sm:pr-0">
      <div>
        <div class="flex justify-between">
          <h3 class="text-sm">
            <%= link_to cart_item.product.name, marketplace_library_path(cart_item.product), class: "font-medium text-gray-700 hover:text-gray-800" %>
          </h3>
        </div>
        <p class="mt-1 text-sm font-medium text-gray-900"><%= humanized_money_with_symbol cart_item.product.price %></p>
      </div>

      <div class="mt-4 sm:mt-0 sm:pr-9">
        <div class="absolute right-0 top-0">
          <%= link_to cart_item_path(cart_item), data: { "turbo-method": :delete }, class: "-m-2 inline-flex p-2 text-gray-400 hover:text-gray-500" do %>
            <span class="sr-only">Remove</span>
            <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
            </svg>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/cart_items/index.html.erb
<main class="mx-auto max-w-2xl px-4 pb-24 pt-16 sm:px-6 lg:max-w-7xl lg:px-8">
  <h1 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Cart</h1>

  <form class="mt-12 lg:grid lg:grid-cols-12 lg:items-start lg:gap-x-12 xl:gap-x-16">
    <section aria-labelledby="cart-heading" class="lg:col-span-7">
      <h2 id="cart-heading" class="sr-only">Items in your shopping cart</h2>

      <% if @cart_items.exists? %>
        <ul role="list" class="divide-y divide-gray-200 border-b border-t border-gray-200">
          <%= render partial: "cart_items/cart_item", collection: @cart_items, as: :cart_item %>
        </ul>
      <% else %>
        <p>There are no items in the cart.</p>
      <% end %>

    </section>

    <!-- Order summary -->
    <section aria-labelledby="summary-heading" class="mt-16 rounded-lg bg-gray-50 px-4 py-6 sm:p-6 lg:col-span-5 lg:mt-0 lg:p-8">
      <h2 id="summary-heading" class="text-lg font-medium text-gray-900">Order summary</h2>

      <dl class="mt-6 space-y-4">
        <div class="flex items-center justify-between border-t border-gray-200 pt-4">
          <dt class="text-base font-medium text-gray-900">Order total</dt>
          <dd class="text-base font-medium text-gray-900"><%= humanized_money_with_symbol @cart_items.map(&:product).map(&:price).inject(:+) %></dd>
        </div>
      </dl>

      <div class="mt-6">
        <% cart_checkout_form_path = user_signed_in? ? checkout_path : new_user_registration_path %>
        <%= link_to "Checkout", cart_checkout_form_path, class: "text-center block w-full rounded-md border border-transparent bg-indigo-600 px-4 py-3 text-base font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-50" %>
      </div>
    </section>
  </form>
</main>