config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :follows
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  if Rails.env.production?
    constraints(host: /^(?!www\.)/i) do
      match '(*any)', to: redirect { |params, request|
        URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
      }, via: :all
    end
  end
  root "marketplace/home#index"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: 'passwords'
  }
  devise_scope :user do
    get '/password_instructions', to: 'passwords#show_instructions'
    get '/signup_success', to: 'users/registrations#signup_success', as: 'signup_success'
  end
  # config/routes.rb

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get '/sitemap.xml', to: 'application#show_sitemap', format: :xml

  # Defines the root path route ("/")

  get "privacy", to: "home#privacy"
  get "explore", to: "home#explore"
  get "terms", to: "home#terms"
  get "refund_policy", to: "home#refund_policy"
  get "contact", to: "home#contact"
  get "robots.txt", to: "home#robots"

  get "dashboard", to: "dashboard#index"
  get "seller_dashboard", to: "dashboard#seller_dashboard"

  get "complete_registrations", to: "complete_registrations#index"
  put "complete_registration", to: "complete_registrations#update"

  get "complete_developer_registrations", to: "complete_developer_registrations#index"
  put "complete_developer_registration", to: "complete_developer_registrations#update"


  resources :accounts

  resources :products, only: [:index, :show, :edit, :update,:new, :create, :destroy] do
    resources :covers, only: [:create, :destroy], controller: "product_covers"
    post 'like', on: :member
    post 'unlike', on: :member
    get 'search', on: :collection
  end
  get 'search_repositories/(:query)', to: "products#search_repositories"

  resources :subscribed_users, only: :create


  resources :sales, only: [:index, :show]
  resources :funds, only: [:index, :create]
  resources :blogs, param: :slug

  get "coming_soon", to: "coming_soon#index"
  get "index_deploy", to: "coming_soon#index_deploy"
  get "index_jobs", to: "coming_soon#index_jobs"
  get "index_versioning", to: "coming_soon#index_versioning"
  get "index_messages", to: "coming_soon#index_messages"
  get "landing_page", to: "coming_soon#landing_page"
  get "faq", to: "faq#index"
  get "resources", to: "marketplace/home#resources"
  
  namespace :marketplace do
    root "home#index"
    get "browse", to: "browse#index"
    get "browse/popular", to: "browse#popular"
     get "browse/free", to: "browse#free"
      get "browse/premium", to: "browse#premium"
    get "browse/featured", to: "browse#featured"

    get "browse/recent", to: "browse#recent"
    get "browse/languages", to: "browse#languages"
    get "browse/categories", to: "browse#categories"
    resources :creators, only: [:index, :show]
    resources :languages, only: :show, param: :slug
    resources :categories, only: [:show, :create], param: :slug
    resources :library, only: :show, path: "l" do
      resources :reviews, only: [:new, :create]
    end
    resources :purchases, only: [:index]
    resources :cart_items, only: [:index, :create, :destroy]
    get "checkout", to: "checkout#index"
    post "checkout", to: "checkout#create"
    post "refund_payment", to: "checkout#refund"
    get '/success_payment', to: 'checkout#success_payment', as: 'success_payment'
    get '/cancel_payment', to: 'checkout#cancel_payment', as: 'cancel_payment'
    resources :refunds, only: [:new, :create]
    resources :users, only: [:show, :edit, :update, :destroy] do
      resources :products, only: :index, controller: "users/products"
      get :synchronizations, to: "users/synchronizations#show", on: :member
      put :product_activations, to: "users/product_activations#update", on: :member
      member do
        get 'followers', to: 'users#followers', as: 'user_followers'
        get 'followees', to: 'users#followees', as: 'user_followees'
      end
    end
    post '/users/:id/follow', to: "users#follow", as: "follow_user"
    post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
    get "search", to: "search_results#index"
    
    resources :notifications, only: [:index] do
      member do
        get :mark_as_read
      end
      collection do
        get :mark_all_as_read
      end
    end
  end

  # Error Pages
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/refund.rb
# Rails example
class Refund < ApplicationRecord
  belongs_to :product
  belongs_to :user
  has_one_attached :stripe_transaction_screenshot, dependent: :destroy
  
  validates :description, presence: true
  validates :status, inclusion: { in: %w[pending approved denied completed] }

  def approve!
    update!(status: 'completed')
  end

  def deny!
    update!(status: 'denied')
  end

  def self.ransackable_associations(auth_object = nil)
    ["product"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "product_id", "stripe_transaction_screenshot_metadata", "status"] # Add "stripe_transaction_screenshot_metadata" for searching by attachment metadata
  end
end

app/controllers/marketplace/refunds_controller.rb
module Marketplace
class RefundsController < ApplicationController
  def new
    @refund = Refund.new
  end

  def create
    @refund = Refund.new(refund_params)
    @refund.product = Product.find(params[:refund][:product_id]) if params[:refund][:product_id].present?
    @refund.stripe_transaction_screenshot = params[:refund][:stripe_transaction_screenshot] if params[:refund][:stripe_transaction_screenshot].present?
    @refund.user_id = current_user.id

    if @refund.save!
      RefundMailer.notify_admin(@refund, current_user).deliver_now
      current_user.update(state: User.states[:seller])
      redirect_to marketplace_root_path, notice: 'Refund request submitted successfully.'
    else
      render :new
    end
  end

  private

  def refund_params
    params.require(:refund).permit(:description, :stripe_transaction_screenshot, :product_id)
  end
end
end

app/controllers/refunds_controller.rb
class RefundsController < ApplicationController
  def new
    @refund = Refund.new
  end

  def create
    @refund = Refund.new(refund_params)
    @refund.product = Product.find(params[:refund][:product_id]) if params[:refund][:product_id].present?
    @refund.stripe_transaction_screenshot = params[:refund][:stripe_transaction_screenshot] if params[:refund][:stripe_transaction_screenshot].present?
    @refund.user_id = current_user.id

    if @refund.save!
      RefundMailer.notify_admin(@refund, current_user).deliver_now
      redirect_to marketplace_root_path, notice: 'Refund request submitted successfully.'
    else
      render :new
    end
  end

  private

  def refund_params
    params.require(:refund).permit(:description, :stripe_transaction_screenshot, :product_id)
  end
end

app/views/refunds/new.html.erb
<%= form_with(model: @refund, url: refunds_path, method: :post, local: true, html: { class: "max-w-md mx-auto bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4", id: "refund-form" }) do |form| %>
  <div class="mb-4">
    <%= form.label :product_name, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.select :product_id, options_from_collection_for_select(current_user.purchases.map(&:product), 'id', 'name'), { prompt: 'Select Product' }, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", id: "product_name" %>
  </div>
  <div class="mb-4">
    <%= form.label :description, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :description, placeholder: 'Description', class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", id: "product_description" %>
  </div>
  <div class="mb-4">
    <%= form.label :stripe_transaction_screenshot, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.file_field :stripe_transaction_screenshot, accept: 'image/*', class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", id: "stripe_transaction_screenshot" %>
  </div>
  <div class="flex items-center justify-between">
    <%= form.submit 'Submit Refund Request', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
</br>
<% end %>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
$(document).ready(function() {
    $('#refund-form').submit(function(event) {
        event.preventDefault();

        var formData = new FormData();
        formData.append('authenticity_token', $('meta[name=csrf-token]').attr('content'));
        formData.append('refund[product_id]', $('#product_name').val());
        formData.append('refund[description]', $('#product_description').val());
        var fileInput = $('#stripe_transaction_screenshot')[0].files[0];

        if (fileInput) {
            formData.append('refund[stripe_transaction_screenshot]', fileInput);
        }

        $.ajax({
            url: $(this).attr('action'),
            method: 'POST',
            data: formData,
            processData: false,
            contentType: false,
            success: function(data) {
                Swal.fire({
                    icon: 'success',
                    title: 'Success!',
                    text: 'Refund request submitted successfully.',
                    showConfirmButton: false,
                    timer: 1500
                }).then(function() {
                    window.location.href = "<%= funds_path %>";
                });
            },
            error: function(xhr, status, error) {
                Swal.fire({
                    icon: 'error',
                    title: 'Error!',
                    text: 'Something went wrong. Please try again later.'
                });
            }
        });
    });
});
</script>